project_id = "druwytttcxnfpwgyrvmt"

[functions.fitness-ai]
verify_jwt = true

[functions.analyze-photo]
verify_jwt = true

[functions.analyze-physique]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.exercise-search-ai]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.food-photo-ai]
verify_jwt = false

[functions.food-photo-ai-test]
verify_jwt = false

[functions.usda-food-proxy]
verify_jwt = false

[functions.optimize-image]
verify_jwt = true

[functions.support-notification]
verify_jwt = false

[functions.fridge-scan-ai]
verify_jwt = false

